### ISSUE TITLE
Continuous Deployment

### ISSUE THREAD

**Issue by utkzas** [uncertainco/org-website#10]
It would be easy for all of us if we we all come up with continuous deployment of our website. So that live view of the could be done rather than deploying it every time we make changes

We can push to main whenever code is production-ready. https://org-website1.vercel.app/ this will be the Continuous deployment URL

**Features:**

DEVELOP
Run None to run your project locally

PREVIEW
Push to any Git branch other than main to preview changes

SHIP
Push to main to ship changes to production

Please suggest if there's something which needs to be changed @rahulsain @shivangdubey

**Comment by rahulsain** [comment]
@utkzas Is this URL only for seeing LIVE changes, or we can use this as for official website?
One more thing, why it is setting up multiple deploys for the same commit in both dev and main branch?

**Comment by utkzas** [comment]
Every commit will have it's own deployment as far as i have experienced using Vercel.
If it's okay then you may close the issue
