### ISSUE TITLE
Website Homepage and homepage-hyperlinks

### ISSUE THREAD

**Issue by utkzas** [uncertainco/org-website#2]
**Deadline-** Monday, 21-06-2021
As per our discussion the following template is decided and the same is pushed to the repo.
The task for week-2 is 

- [ ] To create website homepage contents similar to the page link I provided on Slack (don't directly copy it, apply your intuition to make it look a bit different)
- [x] To create navbar hyperlinks to temporary dummy page
- [x] To customize footer with correct contact info

~In the mid of the week, i.e. 18-06-2021 at least do half of the work and show it to @rahulsain for approval.~

Work on the corona template(it has premade layout), drop the previous existing template

**Comment by rahulsain** [comment]
We are dropping this layout and proceeding with Corona'20 template. We will expect that these task should be done on new template too.
