### ISSUE TITLE
Sprint 02

### ISSUE THREAD

**Issue by rahulsain** [uncertainco/org-website#8]
Problem/Reference: According to the meeting, we have planned/discussed that we will be working on Corona template(already exist in the code). Please note that use [ lorem ipsum](https://www.lipsum.com/) text when ever you required text unless mentioned, use default image that is already there in template(no need to change that). You only have to edit pre - existing design and hence I think the deadline is enough to complete when you will work in a team.

Task that needs to be done:
- [x] Implement Home Page and design and develop below section in it(It will be our landing Page) (**Urgent**)

- services (it should move screen focus from current position to this id in our home page)
- about us (it should move screen focus from current position to this id in our home page)
- team (it should move screen focus from current position to this id in our home page)

- [x] Implement Navigation Bar and add demo link to  

-  Home  (it should move screen focus from current position to this id in our home page)
-  About Us 
-  Services 
-  Team
-  Portfolio (This page should not be designed for now)
-  Career Page(This page should not be designed for now)
-  Contact Us(right now should be embedded with google forms) (This page should not be designed for now)

- [x] Implement Header which consist of

- Our Logo (Top Left position)
- Navigation Bar

- [x] Implement Footer and add

-  Small Description about us (copy our LinkedIn about us text)
-  Social Media Handle (use only LinkedIn icon and link for now)
-  Location (New Delhi, India)
-  Contact Us (it should redirect to dummy page for now)
-  Any more convenient details (if you find any more details that needs to be added then discuss it with us on slack first)

Use [this ](https://github.com/orgs/uncertainco/teams/web/discussions/2) as a reference or contact @rahulsain on slack

**Remember** to mark these task as **COMPLETE** when you have done the sub task **COMPLETELY**

Assignee: @VarshithMittapalli @19-SajalHarmukh @anonymous2912 
Reporter:  @utkzas @rahulsain
Deadline- Saturday, 26-06-2021

**Comment by anonymous2912** [comment]
I guess we're done with this task.
@rahulsain @utkzas Please take a look and let us know if there's anything left

**Comment by rahulsain** [comment]
@uncertainco/web As the team has completed the task assigned to them on time. I am closing this week issue.
I have reviewed and If I miss anything will be automatically assigned to the team next week.
